# Generated by Django 2.1.4 on 2019-01-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filminformation',
            name='json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
