# Generated by Django 2.1.4 on 2019-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_filminformation_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filminformation',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
